baseURL = "https://swcraftlyon.github.io/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "Compte-rendus des software crafters de Lyon"
theme = "beautifulhugo"
publishDir = "./docs"
summaryLength = 5

[params]
  author = "Software Crafters Lyon"
  hideAuthor = true
